# PLEASE ADJUST THE FOLLOWING PARAMETERS --------------------------------------
#

alf_bin: /prj/tools/biotools/alf/bin/alfsim
no_genes: [100]
no_species: 4
pams: [1, 3, 5, 7, 10, 20, 30, 50] #70, 90, 100
si_k_neighborhood: [5, 10, 50]
no_repeats: 10
transposition_rate: 0.01

#
# DON'T TOUCH UNLESS YOU KNOW WHAT YOU'RE DOING -------------------------------
script_dir: scripts

