# PLEASE ADJUST THE FOLLOWING PARAMETERS --------------------------------------
#

alf_bin: /prj/tools/biotools/alf/bin/alfsim
no_genes: [1000]
no_repeats: 500
no_species: 10
pams: [0.5, 1, 3, 5, 7, 10, 20, 30, 50]
si_k_neighborhood: [10, 50, 100]
transposition_rate: 0.01

#
# DON'T TOUCH UNLESS YOU KNOW WHAT YOU'RE DOING -------------------------------
script_dir: scripts

