# PLEASE ADJUST THE FOLLOWING PARAMETERS --------------------------------------
#

alf_bin: /prj/tools/biotools/alf/bin/alfsim
no_genes: [1000]
no_repeats: 10
no_species: 10
pams: [1, 3, 5, 7, 10, 20, 30, 50] #70, 90, 100
si_k_neighborhood: [5, 10, 50]
transposition_rate: 0.01
unimog_jar: software/UniMoG.jar

#
# DON'T TOUCH UNLESS YOU KNOW WHAT YOU'RE DOING -------------------------------
script_dir: scripts

